apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: advanced-data
  namespace: devops-advanced
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: standard
  resources:
    requests:
      storage: 500Mi
